@startuml package_diagram

class GUI

package source.Payment {
    Order "1..*" o-- "1..*" source.Food.Food
    Menu "1" o-- "1..*" source.Food.Food
    Menu "1" --o "1" .GUI
}

package source.Food {
    Dish --|> Food: extends
    Combo --|> Food: extends
    Dish  "1..*" -o "1..*" Combo
}

package source.Management {
    Unit "1" -* "1..*" Cost
    Revenue --> Income
    Cost --> Income
    Order "1..*" --o "1" .GUI
    Cost "1" --o "1" .GUI
    Revenue "1" --o "1" .GUI
    Income "1" --o "1" .GUI
}

@enduml
