package source;


import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GraphicsEnvironment;
import java.awt.Insets;
import java.awt.Rectangle;
import java.awt.Window;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ScrollPaneLayout;
import javax.swing.SwingConstants;
import javax.swing.plaf.IconUIResource;
import javax.swing.plaf.basic.BasicScrollBarUI;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 84909
 */
public class GUI extends javax.swing.JFrame {
    
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        styleTable(tbl_cash, sp_cash);
        styleTable(tbl_order, sp_order);
        
        /*
           for ( Window w : Window.getWindows() ) {
                GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().setFullScreenWindow( w );
        }
        */

        text_cash_search.addKeyListener(new KeyAdapter()
        {
            @Override
            public void keyPressed(KeyEvent e){
                /*
                *** call function search(text_cash_search.getText());
                */
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jMenu1 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        Left = new jPanelGradient();
        btn_menu = new javax.swing.JPanel();
        ind_menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_cash = new javax.swing.JPanel();
        ind_cash = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_cost = new javax.swing.JPanel();
        ind_cost = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_financial = new javax.swing.JPanel();
        ind_financial = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        text_date = new javax.swing.JLabel();
        text_time = new javax.swing.JLabel();
        btn_revenue = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        text_money = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btn_purchase = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        text_orders = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Top = new jPanelGradient(Color.WHITE, new Color(242,245,252));
        btn_exit = new javax.swing.JPanel();
        icon_exit = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new jPanelGradient();
        text_layout_name = new javax.swing.JLabel();
        CenterLayout = new javax.swing.JPanel();
        pn_menu = new javax.swing.JPanel();
        pn_financial = new javax.swing.JPanel();
        pn_cost = new javax.swing.JPanel();
        pn_cash = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btn_subtract = new javax.swing.JLabel();
        btn_plus = new javax.swing.JLabel();
        text_quantity = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btn_add = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new jPanelGradient();
        jLabel16 = new javax.swing.JLabel();
        text_cash_search = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        sp_cash = new javax.swing.JScrollPane();
        tbl_cash = new javax.swing.JTable()
        {
            @Override
            public Component prepareRenderer(TableCellRenderer renderer, int row, int column) {
                // Only called if there are rows present
                JComponent c = (JComponent) super.prepareRenderer(renderer, row, column);
                // Use custom rendering to overcome background color bug in Nimbus
                if (!isRowSelected(row)) {
                    c.setBackground((row % 2 != 0) ? new Color(254,218,196,50) : Color.WHITE);
                    c.setOpaque(true);
                }
                return c;
            }
        };
        jPanel12 = new jPanelGradient();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        sp_order = new javax.swing.JScrollPane();
        tbl_order = new javax.swing.JTable(){
            @Override
            public Component prepareRenderer(TableCellRenderer renderer, int row, int column) {
                // Only called if there are rows present
                JComponent c = (JComponent) super.prepareRenderer(renderer, row, column);
                // Use custom rendering to overcome background color bug in Nimbus
                if (!isRowSelected(row)) {
                    c.setBackground((row % 2 != 0) ? new Color(254,218,196,50) : Color.WHITE);
                    c.setOpaque(true);
                }
                return c;
            }
        };
        jPanel15 = new jPanelGradient();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel16 = new javax.swing.JPanel();
        btn_cancel = new javax.swing.JLabel();
        btn_return = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new jPanelGradient();
        text_total = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btn_charge = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        Left.setBackground(new java.awt.Color(255, 157, 128));
        Left.setPreferredSize(new java.awt.Dimension(240, 665));

        btn_menu.setBackground(new java.awt.Color(255, 148, 122));
        btn_menu.setOpaque(false);
        btn_menu.setPreferredSize(new java.awt.Dimension(240, 45));
        btn_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_menuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_menuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_menuMousePressed(evt);
            }
        });

        ind_menu.setPreferredSize(new java.awt.Dimension(5, 45));

        javax.swing.GroupLayout ind_menuLayout = new javax.swing.GroupLayout(ind_menu);
        ind_menu.setLayout(ind_menuLayout);
        ind_menuLayout.setHorizontalGroup(
            ind_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind_menuLayout.setVerticalGroup(
            ind_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_cutlery_25px.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Menu");
        jLabel2.setPreferredSize(new java.awt.Dimension(122, 30));
        jLabel2.setRequestFocusEnabled(false);

        javax.swing.GroupLayout btn_menuLayout = new javax.swing.GroupLayout(btn_menu);
        btn_menu.setLayout(btn_menuLayout);
        btn_menuLayout.setHorizontalGroup(
            btn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_menuLayout.createSequentialGroup()
                .addComponent(ind_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn_menuLayout.setVerticalGroup(
            btn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(ind_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btn_cash.setBackground(new java.awt.Color(255, 148, 122));
        btn_cash.setOpaque(false);
        btn_cash.setPreferredSize(new java.awt.Dimension(240, 45));
        btn_cash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_cashMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_cashMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_cashMousePressed(evt);
            }
        });

        ind_cash.setBackground(new java.awt.Color(255, 255, 255));
        ind_cash.setOpaque(false);
        ind_cash.setPreferredSize(new java.awt.Dimension(5, 45));

        javax.swing.GroupLayout ind_cashLayout = new javax.swing.GroupLayout(ind_cash);
        ind_cash.setLayout(ind_cashLayout);
        ind_cashLayout.setHorizontalGroup(
            ind_cashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind_cashLayout.setVerticalGroup(
            ind_cashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_expensive_price_25px.png"))); // NOI18N

        jLabel4.setBackground(new java.awt.Color(255, 157, 128));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cash Counter");
        jLabel4.setPreferredSize(new java.awt.Dimension(122, 30));
        jLabel4.setRequestFocusEnabled(false);

        javax.swing.GroupLayout btn_cashLayout = new javax.swing.GroupLayout(btn_cash);
        btn_cash.setLayout(btn_cashLayout);
        btn_cashLayout.setHorizontalGroup(
            btn_cashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_cashLayout.createSequentialGroup()
                .addComponent(ind_cash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn_cashLayout.setVerticalGroup(
            btn_cashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ind_cash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btn_cost.setBackground(new java.awt.Color(255, 157, 128));
        btn_cost.setOpaque(false);
        btn_cost.setPreferredSize(new java.awt.Dimension(240, 45));
        btn_cost.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_costMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_costMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_costMousePressed(evt);
            }
        });

        ind_cost.setBackground(new java.awt.Color(255, 255, 255));
        ind_cost.setOpaque(false);
        ind_cost.setPreferredSize(new java.awt.Dimension(5, 45));

        javax.swing.GroupLayout ind_costLayout = new javax.swing.GroupLayout(ind_cost);
        ind_cost.setLayout(ind_costLayout);
        ind_costLayout.setHorizontalGroup(
            ind_costLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind_costLayout.setVerticalGroup(
            ind_costLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_withdrawal_25px.png"))); // NOI18N

        jLabel6.setBackground(new java.awt.Color(255, 157, 128));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Cost Management");
        jLabel6.setPreferredSize(new java.awt.Dimension(122, 30));
        jLabel6.setRequestFocusEnabled(false);

        javax.swing.GroupLayout btn_costLayout = new javax.swing.GroupLayout(btn_cost);
        btn_cost.setLayout(btn_costLayout);
        btn_costLayout.setHorizontalGroup(
            btn_costLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_costLayout.createSequentialGroup()
                .addComponent(ind_cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn_costLayout.setVerticalGroup(
            btn_costLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ind_cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btn_financial.setBackground(new java.awt.Color(255, 157, 128));
        btn_financial.setOpaque(false);
        btn_financial.setPreferredSize(new java.awt.Dimension(240, 45));
        btn_financial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_financialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_financialMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_financialMousePressed(evt);
            }
        });

        ind_financial.setBackground(new java.awt.Color(255, 255, 255));
        ind_financial.setOpaque(false);
        ind_financial.setPreferredSize(new java.awt.Dimension(5, 45));

        javax.swing.GroupLayout ind_financialLayout = new javax.swing.GroupLayout(ind_financial);
        ind_financial.setLayout(ind_financialLayout);
        ind_financialLayout.setHorizontalGroup(
            ind_financialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind_financialLayout.setVerticalGroup(
            ind_financialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_financial_growth_analysis_25px.png"))); // NOI18N

        jLabel8.setBackground(new java.awt.Color(255, 157, 128));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Financial Analysis");
        jLabel8.setPreferredSize(new java.awt.Dimension(122, 30));
        jLabel8.setRequestFocusEnabled(false);

        javax.swing.GroupLayout btn_financialLayout = new javax.swing.GroupLayout(btn_financial);
        btn_financial.setLayout(btn_financialLayout);
        btn_financialLayout.setHorizontalGroup(
            btn_financialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_financialLayout.createSequentialGroup()
                .addComponent(ind_financial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn_financialLayout.setVerticalGroup(
            btn_financialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ind_financial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        text_date.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        text_date.setForeground(new java.awt.Color(255, 255, 255));
        text_date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_date.setText("12/05/2020");

        text_time.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
        text_time.setForeground(new java.awt.Color(255, 255, 255));
        text_time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_time.setText("10:11");

        btn_revenue.setBackground(new java.awt.Color(255, 148, 122));
        btn_revenue.setOpaque(false);
        btn_revenue.setPreferredSize(new java.awt.Dimension(180, 87));
        btn_revenue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_revenueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_revenueMouseExited(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(220, 5));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Revenue");

        text_money.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        text_money.setForeground(new java.awt.Color(255, 255, 255));
        text_money.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        text_money.setText("4000");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Today");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_money_bag_30px.png"))); // NOI18N

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Thousand VND");

        javax.swing.GroupLayout btn_revenueLayout = new javax.swing.GroupLayout(btn_revenue);
        btn_revenue.setLayout(btn_revenueLayout);
        btn_revenueLayout.setHorizontalGroup(
            btn_revenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
            .addGroup(btn_revenueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btn_revenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btn_revenueLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19))
                    .addGroup(btn_revenueLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(btn_revenueLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_money, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(6, 6, 6))
        );
        btn_revenueLayout.setVerticalGroup(
            btn_revenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_revenueLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGroup(btn_revenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(text_money)
                    .addGroup(btn_revenueLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(btn_revenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel19))
                .addGap(6, 6, 6))
        );

        btn_purchase.setBackground(new java.awt.Color(255, 148, 122));
        btn_purchase.setOpaque(false);
        btn_purchase.setPreferredSize(new java.awt.Dimension(180, 87));
        btn_purchase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_purchaseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_purchaseMouseExited(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(220, 5));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Purchase");

        text_orders.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        text_orders.setForeground(new java.awt.Color(255, 255, 255));
        text_orders.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        text_orders.setText("20");

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Today");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_purchase_order_30px.png"))); // NOI18N

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Orders");

        javax.swing.GroupLayout btn_purchaseLayout = new javax.swing.GroupLayout(btn_purchase);
        btn_purchase.setLayout(btn_purchaseLayout);
        btn_purchaseLayout.setHorizontalGroup(
            btn_purchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
            .addGroup(btn_purchaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btn_purchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btn_purchaseLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel20))
                    .addComponent(jLabel15)
                    .addGroup(btn_purchaseLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(text_orders, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
        );
        btn_purchaseLayout.setVerticalGroup(
            btn_purchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_purchaseLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGroup(btn_purchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(text_orders)
                    .addGroup(btn_purchaseLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(btn_purchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel20))
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout LeftLayout = new javax.swing.GroupLayout(Left);
        Left.setLayout(LeftLayout);
        LeftLayout.setHorizontalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_menu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cash, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_financial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(LeftLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_revenue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_purchase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_date, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(text_time, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        LeftLayout.setVerticalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btn_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_cash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_financial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140)
                .addComponent(btn_revenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btn_purchase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 24, Short.MAX_VALUE)
                .addComponent(text_time, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(text_date)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        Top.setBackground(new java.awt.Color(242, 245, 252));
        Top.setPreferredSize(new java.awt.Dimension(1280, 55));
        Top.setRequestFocusEnabled(false);
        Top.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                TopMouseDragged(evt);
            }
        });
        Top.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TopMousePressed(evt);
            }
        });

        btn_exit.setBackground(new java.awt.Color(232, 17, 35));
        btn_exit.setOpaque(false);
        btn_exit.setPreferredSize(new java.awt.Dimension(45, 35));
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_exitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_exitMousePressed(evt);
            }
        });

        icon_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_delete_15px.png"))); // NOI18N

        javax.swing.GroupLayout btn_exitLayout = new javax.swing.GroupLayout(btn_exit);
        btn_exit.setLayout(btn_exitLayout);
        btn_exitLayout.setHorizontalGroup(
            btn_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon_exit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );
        btn_exitLayout.setVerticalGroup(
            btn_exitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon_exit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_cafe_55px.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 32)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CAFETERIA");

        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(280, 55));

        jPanel7.setBackground(new java.awt.Color(255, 157, 128));
        jPanel7.setPreferredSize(new java.awt.Dimension(280, 5));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        text_layout_name.setFont(new java.awt.Font("Century Gothic", 1, 26)); // NOI18N
        text_layout_name.setForeground(new java.awt.Color(255, 157, 128));
        text_layout_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_layout_name.setText("MENU");
        text_layout_name.setPreferredSize(new java.awt.Dimension(280, 50));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(text_layout_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(text_layout_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout TopLayout = new javax.swing.GroupLayout(Top);
        Top.setLayout(TopLayout);
        TopLayout.setHorizontalGroup(
            TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(385, 385, 385)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        TopLayout.setVerticalGroup(
            TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(TopLayout.createSequentialGroup()
                .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        CenterLayout.setPreferredSize(new java.awt.Dimension(1040, 665));
        CenterLayout.setLayout(new java.awt.CardLayout());

        pn_menu.setPreferredSize(new java.awt.Dimension(1040, 675));

        javax.swing.GroupLayout pn_menuLayout = new javax.swing.GroupLayout(pn_menu);
        pn_menu.setLayout(pn_menuLayout);
        pn_menuLayout.setHorizontalGroup(
            pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
        );
        pn_menuLayout.setVerticalGroup(
            pn_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 665, Short.MAX_VALUE)
        );

        CenterLayout.add(pn_menu, "card2");
        pn_menu.getAccessibleContext().setAccessibleName("");

        pn_financial.setPreferredSize(new java.awt.Dimension(1040, 675));

        javax.swing.GroupLayout pn_financialLayout = new javax.swing.GroupLayout(pn_financial);
        pn_financial.setLayout(pn_financialLayout);
        pn_financialLayout.setHorizontalGroup(
            pn_financialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
        );
        pn_financialLayout.setVerticalGroup(
            pn_financialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 665, Short.MAX_VALUE)
        );

        CenterLayout.add(pn_financial, "card5");

        pn_cost.setPreferredSize(new java.awt.Dimension(1040, 675));

        javax.swing.GroupLayout pn_costLayout = new javax.swing.GroupLayout(pn_cost);
        pn_cost.setLayout(pn_costLayout);
        pn_costLayout.setHorizontalGroup(
            pn_costLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
        );
        pn_costLayout.setVerticalGroup(
            pn_costLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 665, Short.MAX_VALUE)
        );

        CenterLayout.add(pn_cost, "card4");

        pn_cash.setBackground(new java.awt.Color(255, 255, 255));
        pn_cash.setPreferredSize(new java.awt.Dimension(1040, 665));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(680, 65));

        jPanel4.setBackground(new java.awt.Color(242, 245, 252));
        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(345, 40));

        btn_subtract.setBackground(new java.awt.Color(255, 157, 128));
        btn_subtract.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_subtract.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_subtract_25px.png"))); // NOI18N
        btn_subtract.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 157, 128), 3, true));
        btn_subtract.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_subtract.setPreferredSize(new java.awt.Dimension(50, 40));
        btn_subtract.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_subtractMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_subtractMouseExited(evt);
            }
        });

        btn_plus.setBackground(new java.awt.Color(255, 157, 128));
        btn_plus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_plus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_plus_math_25px.png"))); // NOI18N
        btn_plus.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 157, 128), 3, true));
        btn_plus.setPreferredSize(new java.awt.Dimension(50, 40));
        btn_plus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_plusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_plusMouseExited(evt);
            }
        });

        text_quantity.setBackground(new java.awt.Color(242, 245, 252));
        text_quantity.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        text_quantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        text_quantity.setText("10");
        text_quantity.setBorder(null);
        text_quantity.setOpaque(false);
        text_quantity.setPreferredSize(new java.awt.Dimension(45, 30));
        text_quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_quantityActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 157, 128));
        jPanel5.setPreferredSize(new java.awt.Dimension(45, 3));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        btn_add.setBackground(new java.awt.Color(255, 157, 128));
        btn_add.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_add.setForeground(new java.awt.Color(255, 157, 128));
        btn_add.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_buy_25px.png"))); // NOI18N
        btn_add.setText("ADD");
        btn_add.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 157, 128), 3, true));
        btn_add.setPreferredSize(new java.awt.Dimension(160, 40));
        btn_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_addMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btn_subtract, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(btn_plus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_plus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_subtract, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(text_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setPreferredSize(new java.awt.Dimension(680, 90));
        jPanel11.setRequestFocusEnabled(false);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(550, 45));

        jPanel10.setBackground(new java.awt.Color(255, 157, 128));
        jPanel10.setPreferredSize(new java.awt.Dimension(500, 5));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_search_35px_2.png"))); // NOI18N
        jLabel16.setPreferredSize(new java.awt.Dimension(50, 45));

        text_cash_search.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        text_cash_search.setText("Search");
        text_cash_search.setBorder(null);
        text_cash_search.setPreferredSize(new java.awt.Dimension(60, 38));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_cash_search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(34, 34, 34))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(text_cash_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(680, 510));

        sp_cash.setBackground(new java.awt.Color(255, 255, 255));
        sp_cash.setBorder(null);
        sp_cash.setForeground(new java.awt.Color(255, 255, 255));
        sp_cash.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        sp_cash.setPreferredSize(new java.awt.Dimension(600, 483));
        sp_cash.setVerifyInputWhenFocusTarget(false);

        tbl_cash.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbl_cash.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Category", "Type", "Spec", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_cash.setGridColor(new java.awt.Color(240, 240, 240));
        tbl_cash.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tbl_cash.setPreferredSize(new java.awt.Dimension(600, 450));
        tbl_cash.setRowHeight(25);
        tbl_cash.setSelectionBackground(new java.awt.Color(254, 218, 196));
        tbl_cash.setShowGrid(true);
        tbl_cash.getTableHeader().setReorderingAllowed(false);
        sp_cash.setViewportView(tbl_cash);

        jPanel12.setBackground(new java.awt.Color(255, 157, 128));
        jPanel12.setPreferredSize(new java.awt.Dimension(600, 5));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_cash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(sp_cash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setPreferredSize(new java.awt.Dimension(360, 665));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setPreferredSize(new java.awt.Dimension(320, 100));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 157, 128));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("ORDER");
        jLabel12.setPreferredSize(new java.awt.Dimension(50, 65));

        sp_order.setPreferredSize(new java.awt.Dimension(320, 258));
        sp_order.setRequestFocusEnabled(false);

        tbl_order.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_order.setRowHeight(25);
        tbl_order.setSelectionBackground(new java.awt.Color(254, 218, 196));
        tbl_order.getTableHeader().setReorderingAllowed(false);
        sp_order.setViewportView(tbl_order);

        jPanel15.setBackground(new java.awt.Color(255, 157, 128));
        jPanel15.setPreferredSize(new java.awt.Dimension(320, 5));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 157, 128), 2, true), "NOTES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(255, 157, 128))); // NOI18N
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane4.setPreferredSize(new java.awt.Dimension(320, 90));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setPreferredSize(new java.awt.Dimension(285, 0));
        jTextArea1.setSelectionColor(new java.awt.Color(240, 240, 240));
        jScrollPane4.setViewportView(jTextArea1);

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setPreferredSize(new java.awt.Dimension(160, 90));

        btn_cancel.setBackground(new java.awt.Color(232, 17, 35));
        btn_cancel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_cancel.setForeground(new java.awt.Color(232, 17, 35));
        btn_cancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_trash_25px.png"))); // NOI18N
        btn_cancel.setText("CANCEL");
        btn_cancel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(232, 17, 35), 3, true));
        btn_cancel.setPreferredSize(new java.awt.Dimension(160, 40));
        btn_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_cancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_cancelMouseExited(evt);
            }
        });

        btn_return.setBackground(new java.awt.Color(255, 157, 128));
        btn_return.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btn_return.setForeground(new java.awt.Color(255, 157, 128));
        btn_return.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_return.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_return_purchase_25px.png"))); // NOI18N
        btn_return.setText("RETURN");
        btn_return.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 157, 128), 3, true));
        btn_return.setPreferredSize(new java.awt.Dimension(160, 40));
        btn_return.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_returnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_returnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_return, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addComponent(btn_return, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setPreferredSize(new java.awt.Dimension(140, 85));

        jPanel18.setBackground(new java.awt.Color(255, 157, 128));
        jPanel18.setPreferredSize(new java.awt.Dimension(140, 5));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        text_total.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        text_total.setForeground(new java.awt.Color(255, 157, 128));
        text_total.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        text_total.setText("15000");

        jLabel25.setForeground(new java.awt.Color(255, 157, 128));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText("Thousand VND");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(text_total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(text_total)
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(jLabel25))
        );

        btn_charge.setBackground(new java.awt.Color(19, 155, 91));
        btn_charge.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_charge.setForeground(new java.awt.Color(19, 155, 91));
        btn_charge.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_charge.setText("CHARGE");
        btn_charge.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(19, 155, 91), 3, true));
        btn_charge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_chargeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_chargeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sp_order, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_charge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sp_order, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btn_charge, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout pn_cashLayout = new javax.swing.GroupLayout(pn_cash);
        pn_cash.setLayout(pn_cashLayout);
        pn_cashLayout.setHorizontalGroup(
            pn_cashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_cashLayout.createSequentialGroup()
                .addGroup(pn_cashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pn_cashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, 0)
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_cashLayout.setVerticalGroup(
            pn_cashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_cashLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        CenterLayout.add(pn_cash, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(CenterLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Top, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CenterLayout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_menuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuMousePressed
        indSet(ind_menu);
        indReset(new JPanel[]{ind_cash, ind_cost, ind_financial});
        
        pn_menu.setVisible(true);
        pn_cash.setVisible(false);
        pn_cost.setVisible(false);
        pn_financial.setVisible(false);
        
        text_layout_name.setText("MENU");
    }//GEN-LAST:event_btn_menuMousePressed

    private void btn_cashMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cashMousePressed
        indSet(ind_cash);
        indReset(new JPanel[]{ind_menu, ind_cost, ind_financial});
        
        pn_menu.setVisible(false);
        pn_cash.setVisible(true);
        pn_cost.setVisible(false);
        pn_financial.setVisible(false);
        
        text_layout_name.setText("CASH COUNTER");
    }//GEN-LAST:event_btn_cashMousePressed

    private void btn_costMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_costMousePressed
        indSet(ind_cost);
        indReset(new JPanel[]{ind_menu, ind_cash, ind_financial});
        
        pn_menu.setVisible(false);
        pn_cash.setVisible(false);
        pn_cost.setVisible(true);
        pn_financial.setVisible(false);
        
        text_layout_name.setText("COST MANAGEMENT");
    }//GEN-LAST:event_btn_costMousePressed

    private void btn_financialMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_financialMousePressed
        indSet(ind_financial);
        indReset(new JPanel[]{ind_menu, ind_cash, ind_cost});
        
        pn_menu.setVisible(false);
        pn_cash.setVisible(false);
        pn_cost.setVisible(false);
        pn_financial.setVisible(true);
        
        text_layout_name.setText("FINANCIAL ANALYSIS");
    }//GEN-LAST:event_btn_financialMousePressed

    private void btn_menuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuMouseEntered
        btnHover(btn_menu);
    }//GEN-LAST:event_btn_menuMouseEntered

    private void btn_menuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuMouseExited
        btnResetHover(btn_menu);
    }//GEN-LAST:event_btn_menuMouseExited

    private void btn_cashMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cashMouseEntered
        btnHover(btn_cash);
    }//GEN-LAST:event_btn_cashMouseEntered

    private void btn_cashMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cashMouseExited
        btnResetHover(btn_cash);
    }//GEN-LAST:event_btn_cashMouseExited

    private void btn_costMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_costMouseEntered
        btnHover(btn_cost);
    }//GEN-LAST:event_btn_costMouseEntered

    private void btn_costMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_costMouseExited
        btnResetHover(btn_cost);
    }//GEN-LAST:event_btn_costMouseExited

    private void btn_financialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_financialMouseEntered
        btnHover(btn_financial);
    }//GEN-LAST:event_btn_financialMouseEntered

    private void btn_financialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_financialMouseExited
        btnResetHover(btn_financial);
    }//GEN-LAST:event_btn_financialMouseExited

    private void btn_revenueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_revenueMouseEntered
        btnHover(btn_revenue);
    }//GEN-LAST:event_btn_revenueMouseEntered

    private void btn_revenueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_revenueMouseExited
        btnResetHover(btn_revenue);
    }//GEN-LAST:event_btn_revenueMouseExited

    private void btn_purchaseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_purchaseMouseEntered
        btnHover(btn_purchase);
    }//GEN-LAST:event_btn_purchaseMouseEntered

    private void btn_purchaseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_purchaseMouseExited
        btnResetHover(btn_purchase);
    }//GEN-LAST:event_btn_purchaseMouseExited

    private void btn_exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMousePressed
        System.exit(0);
    }//GEN-LAST:event_btn_exitMousePressed

    private void btn_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseExited
        icon_exit.setIcon( new ImageIcon(getClass().getResource("/images/icons8_delete_15px.png")) ) ;
        btn_exit.setOpaque(false);
    }//GEN-LAST:event_btn_exitMouseExited

    private void btn_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseEntered
        icon_exit.setIcon( new ImageIcon(getClass().getResource("/images/icons8_delete_15px_1.png")) ) ;
        btn_exit.setOpaque(true);
    }//GEN-LAST:event_btn_exitMouseEntered

    int xx, yy;
    
    private void TopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TopMousePressed
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_TopMousePressed

    private void TopMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TopMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx, y-yy);
    }//GEN-LAST:event_TopMouseDragged

    private void text_quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_quantityActionPerformed

    private void btn_subtractMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_subtractMouseEntered
        btn_subtract.setIcon( new ImageIcon(getClass().getResource("/images/icons8_subtract_25px_1.png")) );
        btnHover(btn_subtract);
    }//GEN-LAST:event_btn_subtractMouseEntered

    private void btn_subtractMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_subtractMouseExited
        btn_subtract.setIcon( new ImageIcon(getClass().getResource("/images/icons8_subtract_25px.png")) ) ;
        btnResetHover(btn_subtract);
    }//GEN-LAST:event_btn_subtractMouseExited

    private void btn_plusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_plusMouseEntered
        btn_plus.setIcon( new ImageIcon(getClass().getResource("/images/icons8_plus_math_25px_2.png")) );
        btnHover(btn_plus);
    }//GEN-LAST:event_btn_plusMouseEntered

    private void btn_plusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_plusMouseExited
        btn_plus.setIcon( new ImageIcon(getClass().getResource("/images/icons8_plus_math_25px.png")) );
        btnResetHover(btn_plus);
    }//GEN-LAST:event_btn_plusMouseExited

    private void btn_addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addMouseEntered
        btn_add.setIcon( new ImageIcon(getClass().getResource("/images/icons8_buy_25px_1.png")) );
        btnHover(btn_add);
        btn_add.setForeground(Color.WHITE);
    }//GEN-LAST:event_btn_addMouseEntered

    private void btn_addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addMouseExited
        btn_add.setIcon( new ImageIcon(getClass().getResource("/images/icons8_buy_25px.png")) );
        btnResetHover(btn_add);
        btn_add.setForeground(new Color(255,157,128));
    }//GEN-LAST:event_btn_addMouseExited

    private void btn_returnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_returnMouseEntered
        btn_return.setIcon( new ImageIcon(getClass().getResource("/images/icons8_return_purchase_25px_1.png")) );
        btnHover(btn_return);
        btn_return.setForeground(Color.WHITE);
    }//GEN-LAST:event_btn_returnMouseEntered

    private void btn_returnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_returnMouseExited
        btn_return.setIcon( new ImageIcon(getClass().getResource("/images/icons8_return_purchase_25px.png")) );
        btnResetHover(btn_return);
        btn_return.setForeground(new Color(255,157,128));
    }//GEN-LAST:event_btn_returnMouseExited

    private void btn_cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelMouseEntered
        btn_cancel.setIcon( new ImageIcon(getClass().getResource("/images/icons8_trash_25px_1.png")) );
        btnHover(btn_cancel);
        btn_cancel.setForeground(Color.WHITE);
    }//GEN-LAST:event_btn_cancelMouseEntered

    private void btn_cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelMouseExited
        btn_cancel.setIcon( new ImageIcon(getClass().getResource("/images/icons8_trash_25px.png")) );
        btnResetHover(btn_cancel);
        btn_cancel.setForeground(new Color(232,17,35));
    }//GEN-LAST:event_btn_cancelMouseExited

    private void btn_chargeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_chargeMouseEntered
        btnHover(btn_charge);
        btn_charge.setForeground(Color.WHITE);
    }//GEN-LAST:event_btn_chargeMouseEntered

    private void btn_chargeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_chargeMouseExited
        btnResetHover(btn_charge);
        btn_charge.setForeground(new Color(19,155,91));
    }//GEN-LAST:event_btn_chargeMouseExited
  
   
    class jPanelGradient extends JPanel{
        
        Color color1, color2;

        public jPanelGradient() {
            color1 = new Color(255,216,140);
            color2 = new Color(255,157,128);
        }
        
        public jPanelGradient(Color color1, Color color2){
            this.color1 = color1;
            this.color2 = color2;
        }
        
        protected void paintComponent(Graphics g){
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();
            
            GradientPaint gp = new GradientPaint(0,0,color1, 180, height, color2);
            
            g2d.setPaint(gp);
            g2d.fillRect(0,0,width,height);
        }
        
    }
    
    
    void indSet(JPanel ind){
        ind.setOpaque(true);
        ind.repaint();
    }

    void indReset(JPanel[] ind){
        for(JPanel i: ind){
            i.setOpaque(false);
            i.repaint();
        } 
    }
    
    void btnHover(JPanel btn){
        btn.setOpaque(true);
        btn.repaint();
    }
    
    void btnHover(JLabel btn){
        btn.setOpaque(true);
        btn.repaint();
    }
    
    void btnResetHover(JPanel btn){
        btn.setOpaque(false);
        btn.repaint();
    }
    
    void btnResetHover(JLabel btn){
        btn.setOpaque(false);
        btn.repaint();
    }
     
    void styleTable(JTable tbl, JScrollPane sp){
        tbl.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 16));
        tbl.getTableHeader().setSize(50, 25);
        tbl.getTableHeader().setOpaque(false);
        tbl.getTableHeader().setBackground(new Color(255,157,128,225));
        tbl.getTableHeader().setForeground(Color.WHITE);
        tbl.setGridColor(new Color(240,240,240));
        sp.setBorder(null);
        sp.setBackground(new Color(255,157,128,225));
    }
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    
    
    /*
     *** Program variable define below
     */
     
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CenterLayout;
    private javax.swing.JPanel Left;
    private javax.swing.JPanel Top;
    private javax.swing.JLabel btn_add;
    private javax.swing.JLabel btn_cancel;
    private javax.swing.JPanel btn_cash;
    private javax.swing.JLabel btn_charge;
    private javax.swing.JPanel btn_cost;
    private javax.swing.JPanel btn_exit;
    private javax.swing.JPanel btn_financial;
    private javax.swing.JPanel btn_menu;
    private javax.swing.JLabel btn_plus;
    private javax.swing.JPanel btn_purchase;
    private javax.swing.JLabel btn_return;
    private javax.swing.JPanel btn_revenue;
    private javax.swing.JLabel btn_subtract;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel icon_exit;
    private javax.swing.JPanel ind_cash;
    private javax.swing.JPanel ind_cost;
    private javax.swing.JPanel ind_financial;
    private javax.swing.JPanel ind_menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel pn_cash;
    private javax.swing.JPanel pn_cost;
    private javax.swing.JPanel pn_financial;
    private javax.swing.JPanel pn_menu;
    private javax.swing.JScrollPane sp_cash;
    private javax.swing.JScrollPane sp_order;
    private javax.swing.JTable tbl_cash;
    private javax.swing.JTable tbl_order;
    private javax.swing.JTextField text_cash_search;
    private javax.swing.JLabel text_date;
    private javax.swing.JLabel text_layout_name;
    private javax.swing.JLabel text_money;
    private javax.swing.JLabel text_orders;
    private javax.swing.JTextField text_quantity;
    private javax.swing.JLabel text_time;
    private javax.swing.JLabel text_total;
    // End of variables declaration//GEN-END:variables
}
